'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3620
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace NEvoWeb.Modules.NB_Store

    Partial Public Class AdminProduct

        '''<summary>
        '''pnlList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlList As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''productlist control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents productlist As Global.NEvoWeb.Modules.NB_Store.AdminProductList

        '''<summary>
        '''plhMsg control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plhMsg As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''pnlLang control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlLang As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''selectlang control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents selectlang As Global.NEvoWeb.Modules.NB_Store.SelectLang

        '''<summary>
        '''cmdUpdate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdUpdate As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''cmdCancel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdCancel As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''pnlProductTabs control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlProductTabs As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''phPadding control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phPadding As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''tabs control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tabs As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''lblGeneral control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblGeneral As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblCategories control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCategories As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblModels control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblModels As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblImages control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblImages As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblDocuments control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblDocuments As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblOptions control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblOptions As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblRelatedProducts control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblRelatedProducts As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblAll control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblAll As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''pnlProduct control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlProduct As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''productdetail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents productdetail As Global.NEvoWeb.Modules.NB_Store.AdminProductDetail

        '''<summary>
        '''pnlCategories control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlCategories As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''labelCategory control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents labelCategory As Global.System.Web.UI.UserControl

        '''<summary>
        '''dlCategories control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dlCategories As Global.System.Web.UI.UserControl

        '''<summary>
        '''pnlModel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlModel As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''cmdAddModel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdAddModel As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''txtAddModels control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAddModels As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''dgModel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dgModel As Global.System.Web.UI.WebControls.DataGrid

        '''<summary>
        '''pnlImageCtrl control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlImageCtrl As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''productimage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents productimage As Global.NEvoWeb.Modules.NB_Store.AdminProductImage

        '''<summary>
        '''pnlDocCtrl control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlDocCtrl As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''productdoc control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents productdoc As Global.NEvoWeb.Modules.NB_Store.AdminProductDoc

        '''<summary>
        '''pnlOptions control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlOptions As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''tbloptions control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tbloptions As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''cmdAddOption control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdAddOption As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''txtAddOption control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAddOption As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblAddOption control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblAddOption As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''dgOption control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dgOption As Global.System.Web.UI.WebControls.DataGrid

        '''<summary>
        '''optionvaluesdiv control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents optionvaluesdiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''cmdAddOptionValue control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdAddOptionValue As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''txtAddOptionValue control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAddOptionValue As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblAddOptionValue control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblAddOptionValue As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblSelectedOptionID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSelectedOptionID As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''dgOptionEdit control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dgOptionEdit As Global.System.Web.UI.WebControls.DataGrid

        '''<summary>
        '''pnlRelated control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlRelated As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''cmdAddSelected control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdAddSelected As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''cmdClearSelected control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdClearSelected As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''cmdSelectRelated control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdSelectRelated As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''dgRelated control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dgRelated As Global.System.Web.UI.WebControls.DataGrid
    End Class
End Namespace
