'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3615
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace NEvoWeb.Modules.NB_Store

    Partial Public Class AdminBackup

        '''<summary>
        '''pnlBackup control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlBackup As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''cmdDoBackup control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdDoBackup As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''plAllProducts control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plAllProducts As Global.System.Web.UI.UserControl

        '''<summary>
        '''rbAllProducts control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rbAllProducts As Global.System.Web.UI.WebControls.RadioButton

        '''<summary>
        '''chkExpOrders control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkExpOrders As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plProductImages control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plProductImages As Global.System.Web.UI.UserControl

        '''<summary>
        '''rbProductImages control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rbProductImages As Global.System.Web.UI.WebControls.RadioButton

        '''<summary>
        '''plProductDocs control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plProductDocs As Global.System.Web.UI.UserControl

        '''<summary>
        '''rbProductDocs control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rbProductDocs As Global.System.Web.UI.WebControls.RadioButton

        '''<summary>
        '''plAllOrders control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plAllOrders As Global.System.Web.UI.UserControl

        '''<summary>
        '''rbAllOrders control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rbAllOrders As Global.System.Web.UI.WebControls.RadioButton

        '''<summary>
        '''plShipping control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plShipping As Global.System.Web.UI.UserControl

        '''<summary>
        '''rbShipping control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rbShipping As Global.System.Web.UI.WebControls.RadioButton

        '''<summary>
        '''plPurgeStore control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plPurgeStore As Global.System.Web.UI.UserControl

        '''<summary>
        '''rbPurgeStore control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rbPurgeStore As Global.System.Web.UI.WebControls.RadioButton

        '''<summary>
        '''pnlRestore control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlRestore As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''cmdDoImport control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdDoImport As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''plImportUpdate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plImportUpdate As Global.System.Web.UI.UserControl

        '''<summary>
        '''rbImportUpdate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rbImportUpdate As Global.System.Web.UI.WebControls.RadioButton

        '''<summary>
        '''plImportNew control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plImportNew As Global.System.Web.UI.UserControl

        '''<summary>
        '''rbImportNew control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rbImportNew As Global.System.Web.UI.WebControls.RadioButton

        '''<summary>
        '''plCreateCat control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plCreateCat As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkCreateCat control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkCreateCat As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plArchiveProd control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plArchiveProd As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkArchiveProd control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkArchiveProd As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plXMLFile control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plXMLFile As Global.System.Web.UI.UserControl

        '''<summary>
        '''FileUploadXML control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents FileUploadXML As Global.System.Web.UI.WebControls.FileUpload

        '''<summary>
        '''plZipFile control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plZipFile As Global.System.Web.UI.UserControl

        '''<summary>
        '''FileUploadZip control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents FileUploadZip As Global.System.Web.UI.WebControls.FileUpload

        '''<summary>
        '''plZipDocs control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plZipDocs As Global.System.Web.UI.UserControl

        '''<summary>
        '''FileUploadDocs control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents FileUploadDocs As Global.System.Web.UI.WebControls.FileUpload

        '''<summary>
        '''plImportShipping control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plImportShipping As Global.System.Web.UI.UserControl

        '''<summary>
        '''FileUploadShip control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents FileUploadShip As Global.System.Web.UI.WebControls.FileUpload

        '''<summary>
        '''plImportModel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plImportModel As Global.System.Web.UI.UserControl

        '''<summary>
        '''FileUploadModel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents FileUploadModel As Global.System.Web.UI.WebControls.FileUpload

        '''<summary>
        '''lblMsg control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblMsg As Global.System.Web.UI.WebControls.Label
    End Class
End Namespace
