'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3623
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace NEvoWeb.Modules.NB_Store

    Partial Public Class AdminProductDetail

        '''<summary>
        '''labelManufacturer control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents labelManufacturer As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtManufacturer control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtManufacturer As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''ShowSelectLang2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ShowSelectLang2 As Global.NEvoWeb.Modules.NB_Store.ShowSelectLang

        '''<summary>
        '''ShowSelectLang1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ShowSelectLang1 As Global.NEvoWeb.Modules.NB_Store.ShowSelectLang

        '''<summary>
        '''labelSummary control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents labelSummary As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtSummary control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtSummary As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''ShowSelectLang5 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ShowSelectLang5 As Global.NEvoWeb.Modules.NB_Store.ShowSelectLang

        '''<summary>
        '''plTagWords control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plTagWords As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtTagWords control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtTagWords As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''labelProductName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents labelProductName As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtProductName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtProductName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''ShowSelectLang control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ShowSelectLang As Global.NEvoWeb.Modules.NB_Store.ShowSelectLang

        '''<summary>
        '''labelSEOName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents labelSEOName As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtSEOName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtSEOName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''ShowSelectLang4 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ShowSelectLang4 As Global.NEvoWeb.Modules.NB_Store.ShowSelectLang

        '''<summary>
        '''labelProductRef control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents labelProductRef As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtProductRef control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtProductRef As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plTaxCategory control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plTaxCategory As Global.System.Web.UI.UserControl

        '''<summary>
        '''cmbCategory control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmbCategory As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''labelArchived control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents labelArchived As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkArchived control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkArchived As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''labelFeatured control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents labelFeatured As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkFeatured control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkFeatured As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''labelDeleted control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents labelDeleted As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkDeleted control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkDeleted As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plIsHidden control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plIsHidden As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkIsHidden control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkIsHidden As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''dlXMLData control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dlXMLData As Global.System.Web.UI.WebControls.DataList

        '''<summary>
        '''dshEditor control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dshEditor As Global.System.Web.UI.UserControl

        '''<summary>
        '''tblDescription control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblDescription As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''ShowSelectLang3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ShowSelectLang3 As Global.NEvoWeb.Modules.NB_Store.ShowSelectLang

        '''<summary>
        '''labelDescription control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents labelDescription As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtDescription control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtDescription As Global.System.Web.UI.UserControl
    End Class
End Namespace
