'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3623
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace NEvoWeb.Modules.NB_Store

    Partial Public Class AdminOrders

        '''<summary>
        '''pnlOrderList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlOrderList As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''cmdReturn control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdReturn As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''cmdCreate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdCreate As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''lblOrderNbr control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblOrderNbr As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtOrderNbr control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtOrderNbr As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblName As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtFilter control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtFilter As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''ddlSearch control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlSearch As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''lblFrom control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblFrom As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtFromDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtFromDate As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''hypFromDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hypFromDate As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''cvFromDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cvFromDate As Global.System.Web.UI.WebControls.CompareValidator

        '''<summary>
        '''lblTo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTo As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtToDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtToDate As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''hypToDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hypToDate As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''cvToDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cvToDate As Global.System.Web.UI.WebControls.CompareValidator

        '''<summary>
        '''cmdSelect control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdSelect As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''dgOrderList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dgOrderList As Global.System.Web.UI.WebControls.DataGrid

        '''<summary>
        '''pnlOrderEdit control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlOrderEdit As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''cmdEditOrder control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdEditOrder As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''cmdUpdate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdUpdate As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''cmdReturn2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdReturn2 As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''cmdReOrder control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdReOrder As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''cmdPrintOrder control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdPrintOrder As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''cmdPrintreceipt control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdPrintreceipt As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''lblPopupMsg control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPopupMsg As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''pnlUpdate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlUpdate As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''cmdSendAmendEmail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdSendAmendEmail As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''cmdSendValidateOrder control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdSendValidateOrder As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''cmdSendShipEmail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdSendShipEmail As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''cmdSendReceiptEmail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdSendReceiptEmail As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''lblShipDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblShipDate As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtShipDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtShipDate As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''hypShipDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hypShipDate As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''lblTrackCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTrackCode As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtTrackCode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtTrackCode As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''CompareValidator1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CompareValidator1 As Global.System.Web.UI.WebControls.CompareValidator

        '''<summary>
        '''lblStatus control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblStatus As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''ddlStatus control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlStatus As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''pnlEdit control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlEdit As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''EditBAddrForm control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents EditBAddrForm As Global.NEvoWeb.Modules.NB_Store.Address

        '''<summary>
        '''EditSAddrForm control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents EditSAddrForm As Global.NEvoWeb.Modules.NB_Store.Address

        '''<summary>
        '''lblOrderEmail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblOrderEmail As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtOrderEmail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtOrderEmail As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtEditNoteMsg control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtEditNoteMsg As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''cartlist1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cartlist1 As Global.NEvoWeb.Modules.NB_Store.CartList

        '''<summary>
        '''cmdAddProduct control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdAddProduct As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''lblAlreadyPaid control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblAlreadyPaid As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtAlreadyPaid control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAlreadyPaid As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plhOrder control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plhOrder As Global.System.Web.UI.WebControls.PlaceHolder
    End Class
End Namespace
