'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3623
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace NEvoWeb.Modules.NB_Store

    Partial Public Class AdminHost

        '''<summary>
        '''PlaceHolder1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PlaceHolder1 As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''pnlHost control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlHost As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lblGeneral control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblGeneral As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblSettings control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSettings As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblReports control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblReports As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtPass control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtPass As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''cmdClearStore control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdClearStore As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''lblInvalidPass control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblInvalidPass As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''cmdRestart control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdRestart As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''cmdClearTempUpload control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdClearTempUpload As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''cmdCalcSale control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdCalcSale As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''cmdCreateThumbs control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdCreateThumbs As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''cmdPurgeFiles control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdPurgeFiles As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''cmdValidation control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdValidation As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''chkValidation control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkValidation As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''lblValidationMsg control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblValidationMsg As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''fupTemplate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents fupTemplate As Global.System.Web.UI.WebControls.FileUpload

        '''<summary>
        '''cmdImportDefault control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdImportDefault As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''chkOverwriteSettings control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkOverwriteSettings As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''cmdSaveSettings control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdSaveSettings As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''cmdClearSettings control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdClearSettings As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''pnlCheckBoxLists control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlCheckBoxLists As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lblLang control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblLang As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''chkLlang control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkLlang As Global.System.Web.UI.WebControls.CheckBoxList

        '''<summary>
        '''chkSelectAll control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkSelectAll As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''lblchkSettings control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblchkSettings As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''chkLsettings control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkLsettings As Global.System.Web.UI.WebControls.CheckBoxList

        '''<summary>
        '''chkSelectAllT control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkSelectAllT As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''lblTemplates control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTemplates As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''chkLtemplates control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkLtemplates As Global.System.Web.UI.WebControls.CheckBoxList

        '''<summary>
        '''cmdUpgradeAll control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdUpgradeAll As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''dgPortals control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dgPortals As Global.System.Web.UI.WebControls.DataGrid

        '''<summary>
        '''fupReports control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents fupReports As Global.System.Web.UI.WebControls.FileUpload

        '''<summary>
        '''cmdImportReports control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdImportReports As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''chkOverwriteReport control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkOverwriteReport As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''cmdExportReport control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdExportReport As Global.System.Web.UI.WebControls.LinkButton
    End Class
End Namespace
