'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3603
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace NEvoWeb.Modules.NB_Store

    Partial Public Class CategoryMenu

        '''<summary>
        '''phRootHead control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phRootHead As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''dlRootMenu control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dlRootMenu As Global.System.Web.UI.WebControls.DataList

        '''<summary>
        '''phSecSep1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phSecSep1 As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''lblBreadcrumbs control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblBreadcrumbs As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''phSecSep2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phSecSep2 As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''phSubHead control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phSubHead As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''dlCategoryMenu control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dlCategoryMenu As Global.System.Web.UI.WebControls.DataList

        '''<summary>
        '''phSecSep3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phSecSep3 As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''phTreeHead control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phTreeHead As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''phTreeMenu control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phTreeMenu As Global.System.Web.UI.WebControls.PlaceHolder
    End Class
End Namespace
