'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3615
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace NEvoWeb.Modules.NB_Store

    Partial Public Class CategoryMenuSettings

        '''<summary>
        '''plDefaultCategory control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plDefaultCategory As Global.System.Web.UI.UserControl

        '''<summary>
        '''ddlDefaultCategory control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlDefaultCategory As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''plStaticCategory control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plStaticCategory As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkStaticCategory control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkStaticCategory As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plHideBreadCrumb control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plHideBreadCrumb As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkHideBreadCrumb control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkHideBreadCrumb As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plHideBreadCrumbRoot control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plHideBreadCrumbRoot As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkHideBreadCrumbRoot control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkHideBreadCrumbRoot As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plBreadCrumbCSS control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plBreadCrumbCSS As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtBreadCrumbCSS control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtBreadCrumbCSS As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plBreadCrumbSep control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plBreadCrumbSep As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtBreadCrumbSep control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtBreadCrumbSep As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plHideRootMenu control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plHideRootMenu As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkHideRootMenu control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkHideRootMenu As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plPatchWork control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plPatchWork As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkPatchWork control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkPatchWork As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plRootCSS control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plRootCSS As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtRootCSS control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtRootCSS As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plRootSelectCSS control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plRootSelectCSS As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtRootSelectCSS control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtRootSelectCSS As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plRootSep control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plRootSep As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtRootSep control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtRootSep As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plRootLeftHtml control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plRootLeftHtml As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtRootLeftHtml control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtRootLeftHtml As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plRootNameTemplate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plRootNameTemplate As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtRootNameTemplate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtRootNameTemplate As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plRootRightHtml control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plRootRightHtml As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtRootRightHtml control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtRootRightHtml As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plRootHeadHtml control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plRootHeadHtml As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtRootHeadHtml control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtRootHeadHtml As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plHideSubMenu control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plHideSubMenu As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkHideSubMenu control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkHideSubMenu As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plHideWhenRoot control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plHideWhenRoot As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkHideWhenRoot control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkHideWhenRoot As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plCSS control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plCSS As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtCSS control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCSS As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plSubSelectCSS control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plSubSelectCSS As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtSubSelectCSS control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtSubSelectCSS As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plSep control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plSep As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtSep control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtSep As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plSubLeftHtml control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plSubLeftHtml As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtSubLeftHtml control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtSubLeftHtml As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plSubNameTemplate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plSubNameTemplate As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtSubNameTemplate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtSubNameTemplate As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plSubRightHtml control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plSubRightHtml As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtSubRightHtml control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtSubRightHtml As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plSubHeadHtml control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plSubHeadHtml As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtSubHeadHtml control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtSubHeadHtml As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plShowTreeMenu control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plShowTreeMenu As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkShowTreeMenu control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkShowTreeMenu As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plTreeCSS control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plTreeCSS As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtTreeCSS control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtTreeCSS As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plTreeSelectCSS control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plTreeSelectCSS As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtTreeSelectCSS control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtTreeSelectCSS As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plTreeLeftHtml control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plTreeLeftHtml As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtTreeLeftHtml control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtTreeLeftHtml As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plTreeNameTemplate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plTreeNameTemplate As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtTreeNameTemplate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtTreeNameTemplate As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plTreeRightHtml control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plTreeRightHtml As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtTreeRightHtml control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtTreeRightHtml As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plTreeHeadHtml control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plTreeHeadHtml As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtTreeHeadHtml control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtTreeHeadHtml As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plShowAccordionMenu control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plShowAccordionMenu As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkShowAccordionMenu control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkShowAccordionMenu As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plAccordionLeftHtml control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plAccordionLeftHtml As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtAccordionLeftHtml control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAccordionLeftHtml As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plAccordionNameTemplate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plAccordionNameTemplate As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtAccordionNameTemplate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAccordionNameTemplate As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plAccordionRightHtml control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plAccordionRightHtml As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtAccordionRightHtml control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAccordionRightHtml As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plAccordionHeadHtml control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plAccordionHeadHtml As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtAccordionHeadHtml control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAccordionHeadHtml As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plSkipBlankCat control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plSkipBlankCat As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkSkipBlankCat control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkSkipBlankCat As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plViewProdHide control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plViewProdHide As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkViewProdHide control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkViewProdHide As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plColumns control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plColumns As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtColumns control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtColumns As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plThumbnailSize control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plThumbnailSize As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtThumbnailSize control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtThumbnailSize As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plSectionSep control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plSectionSep As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtSectionSep control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtSectionSep As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plSectionSep2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plSectionSep2 As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtSectionSep2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtSectionSep2 As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plSectionSep3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plSectionSep3 As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtSectionSep3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtSectionSep3 As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plProductTabList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plProductTabList As Global.System.Web.UI.UserControl

        '''<summary>
        '''lstProductTabs control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lstProductTabs As Global.System.Web.UI.WebControls.DropDownList
    End Class
End Namespace
