'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3603
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace NEvoWeb.Modules.NB_Store

    Partial Public Class CheckOutSettings

        '''<summary>
        '''plShowDiscountCol control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plShowDiscountCol As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkShowDiscountCol control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkShowDiscountCol As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plShowShipMethod control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plShowShipMethod As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkShowShipMethod control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkShowShipMethod As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plHideShipInCart control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plHideShipInCart As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkHideShipInCart control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkHideShipInCart As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plHideVAT control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plHideVAT As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkHideVAT control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkHideVAT As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plHidePromo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plHidePromo As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkHidePromo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkHidePromo As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plHideCountry control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plHideCountry As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkHideCountry control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkHideCountry As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plSkipCart control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plSkipCart As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkSkipCart control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkSkipCart As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plHideChq control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plHideChq As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkHideChq control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkHideChq As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plStockChq control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plStockChq As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkStockChq control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkStockChq As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plHideShip control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plHideShip As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkHideShip control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkHideShip As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plNonUserOrder control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plNonUserOrder As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkNonUserOrder control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkNonUserOrder As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plDisableLoginMsg control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plDisableLoginMsg As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkDisableLoginMsg control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkDisableLoginMsg As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plSmoothLogin control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plSmoothLogin As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkSmoothLogin control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkSmoothLogin As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plSmoothLoginTab control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plSmoothLoginTab As Global.System.Web.UI.UserControl

        '''<summary>
        '''ddlSmoothLoginTab control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlSmoothLoginTab As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''plMinimumValidate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plMinimumValidate As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkMinimumValidate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkMinimumValidate As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plHideExtraInfo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plHideExtraInfo As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkHideExtraInfo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkHideExtraInfo As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plShowStageHeader control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plShowStageHeader As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkShowStageHeader control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkShowStageHeader As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plGateway control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plGateway As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkGateway control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkGateway As Global.System.Web.UI.WebControls.CheckBoxList

        '''<summary>
        '''plChequeGateway control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plChequeGateway As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkLEncapGateway control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkLEncapGateway As Global.System.Web.UI.WebControls.CheckBoxList

        '''<summary>
        '''plGatewayDisplay control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plGatewayDisplay As Global.System.Web.UI.UserControl

        '''<summary>
        '''rblGatewayDisplay control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rblGatewayDisplay As Global.System.Web.UI.WebControls.RadioButtonList

        '''<summary>
        '''plTabList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plTabList As Global.System.Web.UI.UserControl

        '''<summary>
        '''lstTabs control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lstTabs As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''plTabContShop control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plTabContShop As Global.System.Web.UI.UserControl

        '''<summary>
        '''lstTabContShop control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lstTabContShop As Global.System.Web.UI.WebControls.DropDownList
    End Class
End Namespace
