'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3620
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace NEvoWeb.Modules.NB_Store

    Partial Public Class MiniCartSettings

        '''<summary>
        '''plFullTemplate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plFullTemplate As Global.System.Web.UI.UserControl

        '''<summary>
        '''ddlFullTemplate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlFullTemplate As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''plEmptyTemplate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plEmptyTemplate As Global.System.Web.UI.UserControl

        '''<summary>
        '''ddlEmptyTemplate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlEmptyTemplate As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''plShowFullCart control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plShowFullCart As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkShowFullCart control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkShowFullCart As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plHideHeader control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plHideHeader As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkHideHeader control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkHideHeader As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plMiniPosition control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plMiniPosition As Global.System.Web.UI.UserControl

        '''<summary>
        '''ddlMiniPosition control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlMiniPosition As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''plShowDiscountCol control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plShowDiscountCol As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkShowDiscountCol control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkShowDiscountCol As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plAllowEdit control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plAllowEdit As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkAllowEdit control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkAllowEdit As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plHideTotal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plHideTotal As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkHideTotal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkHideTotal As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plHideDescriptionCol control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plHideDescriptionCol As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkHideDescriptionCol control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkHideDescriptionCol As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plHidePriceCol control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plHidePriceCol As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkHidePriceCol control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkHidePriceCol As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plHideQtyCol control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plHideQtyCol As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkHideQtyCol control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkHideQtyCol As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plHideRemoveCol control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plHideRemoveCol As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkHideRemoveCol control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkHideRemoveCol As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plHideTotalCol control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plHideTotalCol As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkHideTotalCol control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkHideTotalCol As Global.System.Web.UI.WebControls.CheckBox
    End Class
End Namespace
