'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3620
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace NEvoWeb.Modules.NB_Store

    Partial Public Class ProductList

        '''<summary>
        '''phProductModuleHeader control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phProductModuleHeader As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''pnlProductList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlProductList As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''phProductListHeader control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phProductListHeader As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''plhCatMsg control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plhCatMsg As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''CategoryMenu control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CategoryMenu As Global.NEvoWeb.Modules.NB_Store.CategoryMenu

        '''<summary>
        '''dlProductList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dlProductList As Global.System.Web.UI.WebControls.DataList

        '''<summary>
        '''lblLineBreak control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblLineBreak As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''ctlPagingControl control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ctlPagingControl As Global.DotNetNuke.UI.WebControls.PagingControl

        '''<summary>
        '''pnlSPO control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlSPO As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''phProductDetailHeader control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents phProductDetailHeader As Global.System.Web.UI.WebControls.PlaceHolder

        '''<summary>
        '''dlProductDetail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dlProductDetail As Global.System.Web.UI.WebControls.DataList

        '''<summary>
        '''lblMsg control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblMsg As Global.System.Web.UI.WebControls.Label
    End Class
End Namespace
