'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3623
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace NEvoWeb.Modules.NB_Store

    Partial Public Class ProductListSettings

        '''<summary>
        '''dshBasic control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dshBasic As Global.System.Web.UI.UserControl

        '''<summary>
        '''tblBasic control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblBasic As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''plDefaultCategory control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plDefaultCategory As Global.System.Web.UI.UserControl

        '''<summary>
        '''ddlDefaultCategory control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlDefaultCategory As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''plModuleTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plModuleTitle As Global.System.Web.UI.UserControl

        '''<summary>
        '''lstModuleTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lstModuleTitle As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''plBrowseMode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plBrowseMode As Global.System.Web.UI.UserControl

        '''<summary>
        '''lstBrowseMode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lstBrowseMode As Global.System.Web.UI.WebControls.RadioButtonList

        '''<summary>
        '''plExcludeFeatured control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plExcludeFeatured As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkExcludeFeatured control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkExcludeFeatured As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plExcludeProduct control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plExcludeProduct As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkExcludeProduct control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkExcludeProduct As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plPageSize control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plPageSize As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtPageSize control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtPageSize As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plColumns control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plColumns As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtColumns control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtColumns As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plLayout control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plLayout As Global.System.Web.UI.UserControl

        '''<summary>
        '''ddlLayout control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlLayout As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''plDirection control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plDirection As Global.System.Web.UI.UserControl

        '''<summary>
        '''ddlDirection control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlDirection As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''plDefaultOrder control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plDefaultOrder As Global.System.Web.UI.UserControl

        '''<summary>
        '''ddlDefaultOrder control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlDefaultOrder As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''plDefaultOrderDESC control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plDefaultOrderDESC As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkDefaultOrderDESC control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkDefaultOrderDESC As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plCascadeResults control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plCascadeResults As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkCascadeResults control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkCascadeResults As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''dshTemplates control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dshTemplates As Global.System.Web.UI.UserControl

        '''<summary>
        '''tblTemplates control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblTemplates As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''plTemplate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plTemplate As Global.System.Web.UI.UserControl

        '''<summary>
        '''ddlTemplate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlTemplate As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''plAlterTemplate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plAlterTemplate As Global.System.Web.UI.UserControl

        '''<summary>
        '''ddlAlterTemplate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlAlterTemplate As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''plDetailTemplate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plDetailTemplate As Global.System.Web.UI.UserControl

        '''<summary>
        '''ddlDetailTemplate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlDetailTemplate As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''plStaticTemplates control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plStaticTemplates As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkStaticTemplates control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkStaticTemplates As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plStaticListView control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plStaticListView As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkStaticListView control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkStaticListView As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plHeaderText control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plHeaderText As Global.System.Web.UI.UserControl

        '''<summary>
        '''ddlHeaderText control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlHeaderText As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''plListHeaderText control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plListHeaderText As Global.System.Web.UI.UserControl

        '''<summary>
        '''ddlListHeaderText control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlListHeaderText As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''plDetailHeaderText control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plDetailHeaderText As Global.System.Web.UI.UserControl

        '''<summary>
        '''ddlDetailHeaderText control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlDetailHeaderText As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''dshTabs control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dshTabs As Global.System.Web.UI.UserControl

        '''<summary>
        '''tblTabs control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblTabs As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''plRedirectToCart control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plRedirectToCart As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkRedirectToCart control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkRedirectToCart As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plTabList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plTabList As Global.System.Web.UI.UserControl

        '''<summary>
        '''lstTabs control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lstTabs As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''plchkTabDefaultRedirect control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plchkTabDefaultRedirect As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkTabDefaultRedirect control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkTabDefaultRedirect As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plTabDefaultRedirect control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plTabDefaultRedirect As Global.System.Web.UI.UserControl

        '''<summary>
        '''ddlTabDefaultRedirect control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlTabDefaultRedirect As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''plProductTabList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plProductTabList As Global.System.Web.UI.UserControl

        '''<summary>
        '''lstProductTabs control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lstProductTabs As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''dshOther control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dshOther As Global.System.Web.UI.UserControl

        '''<summary>
        '''Table2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Table2 As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''plThumbnailSize control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plThumbnailSize As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtThumbnailSize control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtThumbnailSize As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plDetailThumbnailSize control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plDetailThumbnailSize As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtDetailThumbnailSize control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtDetailThumbnailSize As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plGalleryThumbnailSize control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plGalleryThumbnailSize As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtGalleryThumbnailSize control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtGalleryThumbnailSize As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plColWidth control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plColWidth As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtColWidth control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtColWidth As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plItemStyleCssClass control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plItemStyleCssClass As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtItemStyleCssClass control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtItemStyleCssClass As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plAlternatingItemStyleCssClass control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plAlternatingItemStyleCssClass As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtAlternatingItemStyleCssClass control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAlternatingItemStyleCssClass As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plCellPadding control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plCellPadding As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtCellPadding control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCellPadding As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plCellSpacing control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plCellSpacing As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtCellSpacing control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCellSpacing As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plItemStyleHorizontalAlign control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plItemStyleHorizontalAlign As Global.System.Web.UI.UserControl

        '''<summary>
        '''ddlItemStyleHorizontalAlign control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlItemStyleHorizontalAlign As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''plItemStyleHeight control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plItemStyleHeight As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtItemStyleHeight control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtItemStyleHeight As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plTableWidth control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plTableWidth As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtTableWidth control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtTableWidth As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plCssClass control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plCssClass As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtCssClass control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCssClass As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plCssBuyButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plCssBuyButton As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtCssBuyButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCssBuyButton As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plCategoryMessage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plCategoryMessage As Global.System.Web.UI.UserControl

        '''<summary>
        '''rblCategoryMessage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rblCategoryMessage As Global.System.Web.UI.WebControls.RadioButtonList

        '''<summary>
        '''plSep1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plSep1 As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtSep control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtSep As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plIncrementCart control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plIncrementCart As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkIncrementCart control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkIncrementCart As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plIndexProducts control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plIndexProducts As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkIndexProducts control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkIndexProducts As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plSkipList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plSkipList As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkSkipList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkSkipList As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plReturnLimit control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plReturnLimit As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtReturnLimit control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtReturnLimit As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''dshSubMenu control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dshSubMenu As Global.System.Web.UI.UserControl

        '''<summary>
        '''Table3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Table3 As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''plShowSubMenu control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plShowSubMenu As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkShowSubMenu control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkShowSubMenu As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plSubColumns control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plSubColumns As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtSubMenuCols control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtSubMenuCols As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plSubThumbnailSize control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plSubThumbnailSize As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtSubThumbnailSize control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtSubThumbnailSize As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plCSS control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plCSS As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtCSS control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCSS As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plSubSelectCSS control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plSubSelectCSS As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtSubSelectCSS control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtSubSelectCSS As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plSep control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plSep As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtSubMenuSep control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtSubMenuSep As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plSubLeftHtml control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plSubLeftHtml As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtSubLeftHtml control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtSubLeftHtml As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plSubNameTemplate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plSubNameTemplate As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtSubNameTemplate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtSubNameTemplate As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plSubRightHtml control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plSubRightHtml As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtSubRightHtml control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtSubRightHtml As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plSubHeadHtml control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plSubHeadHtml As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtSubHeadHtml control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtSubHeadHtml As Global.System.Web.UI.WebControls.TextBox
    End Class
End Namespace
