'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1433
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace NEvoWeb.Modules.NB_Store

    Partial Public Class ProductSearchSettings

        '''<summary>
        '''plModuleCombo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plModuleCombo As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtModule control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtModule As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''cboModule control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cboModule As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''plGoCheck control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plGoCheck As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkGo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkGo As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plImgPath control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plImgPath As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtImagePath control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtImagePath As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plSearchCheck control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plSearchCheck As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkSearchImage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkSearchImage As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plSImgPath control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plSImgPath As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtSImagePath control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtSImagePath As Global.System.Web.UI.WebControls.TextBox
    End Class
End Namespace
