'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3615
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace NEvoWeb.Modules.NB_Store

    Partial Public Class TaxRates

        '''<summary>
        '''pnlEdit control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlEdit As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''cmdUpdate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdUpdate As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''pnlSetup control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlSetup As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''txtTDefault control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtTDefault As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''cvTaxDefault control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cvTaxDefault As Global.System.Web.UI.WebControls.CompareValidator

        '''<summary>
        '''lblTDefaultID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTDefaultID As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''plTDefault control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plTDefault As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtShipTax control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtShipTax As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''cvShipTax control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cvShipTax As Global.System.Web.UI.WebControls.CompareValidator

        '''<summary>
        '''lblShipTaxID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblShipTaxID As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''plShipTax control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plShipTax As Global.System.Web.UI.UserControl

        '''<summary>
        '''lblTOptionsID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTOptionsID As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''rblTaxOptions control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rblTaxOptions As Global.System.Web.UI.WebControls.RadioButtonList

        '''<summary>
        '''pnlProduct control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlProduct As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''txtSearch control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtSearch As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''cmdSearch control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdSearch As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''pnlCategory control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlCategory As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''ddlCategory control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlCategory As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''cmdAddCategory control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdAddCategory As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''pnlRange control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlRange As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''grdRange control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents grdRange As Global.System.Web.UI.WebControls.DataGrid
    End Class
End Namespace
